import { Types } from 'mongoose';
import {
  FoundItemCustodyTypeEnum,
  FoundItemStatusEnum,
} from 'src/found-item/entities/found-item.entity';

export const foundItemsSeed = [
  {
    _id: new Types.ObjectId('6a23d8bdbcbfc47449280461'),
    title: 'Black Samsung phone',
    description:
      'A black Samsung smartphone was found near the library entrance. It has a cracked black case.',
    brand: 'Samsung',
    color: 'Black',
    dateFound: new Date('2026-06-06T08:00:00.000Z'),
    locationFound: 'Library entrance',
    gpsLocation: {
      latitude: -37.8136,
      longitude: 144.9631,
    },
    custodyType: FoundItemCustodyTypeEnum.OFFICE,
    status: FoundItemStatusEnum.REPORTED,
    images: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/SAMSUNG_Galaxy_S22_Ultra_BLACK_%283%29.jpg',
    ],
    identifyingDetails: 'Cracked black phone case',
    category: '69cf8c352d9893a68b332ca2',
    foundBy: new Types.ObjectId('69d4ca5259e9b25307f1fcd6'),
    isPublic: true,
    isActive: true,
    isDeleted: false,
  },
  {
    _id: new Types.ObjectId('6a23d8bdbcbfc47449280462'),
    title: 'Silver Apple MacBook',
    description:
      'A silver Apple MacBook laptop was found in the computer lab after class.',
    brand: 'Apple',
    color: 'Silver',
    dateFound: new Date('2026-06-05T09:30:00.000Z'),
    locationFound: 'Computer Lab',
    gpsLocation: {
      latitude: -37.8137,
      longitude: 144.9632,
    },
    custodyType: FoundItemCustodyTypeEnum.OFFICE,
    status: FoundItemStatusEnum.REPORTED,
    images: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/A_2021_14-inch_Silver_MacBook_Pro_%28cropped%29.jpg',
    ],
    identifyingDetails: 'Small sticker on the laptop cover',
    category: '69cf8c352d9893a68b332ca2',
    foundBy: new Types.ObjectId('69d4ca5259e9b25307f1fcd6'),
    isPublic: true,
    isActive: true,
    isDeleted: false,
  },
  {
    _id: new Types.ObjectId('6a23d8bdbcbfc47449280463'),
    title: 'White USB-C charger',
    description:
      'A white USB-C phone charger was found under a desk in Lecture Hall 2.',
    brand: 'Unknown',
    color: 'White',
    dateFound: new Date('2026-06-06T10:15:00.000Z'),
    locationFound: 'Lecture Hall 2',
    gpsLocation: {
      latitude: -37.8138,
      longitude: 144.9633,
    },
    custodyType: FoundItemCustodyTypeEnum.OFFICE,
    status: FoundItemStatusEnum.REPORTED,
    images: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/USB-C_cable_2017_A.jpg',
    ],
    identifyingDetails: 'White charging cable attached',
    category: '69cf8c352d9893a68b332ca2',
    foundBy: new Types.ObjectId('69d4ca5259e9b25307f1fcd6'),
    isPublic: true,
    isActive: true,
    isDeleted: false,
  },
  {
    _id: new Types.ObjectId('6a23d8bdbcbfc47449280464'),
    title: 'Brown leather wallet',
    description:
      'A brown leather wallet was found near the cafeteria seating area.',
    brand: 'Unknown',
    color: 'Brown',
    dateFound: new Date('2026-06-04T07:45:00.000Z'),
    locationFound: 'Cafeteria',
    gpsLocation: {
      latitude: -37.8139,
      longitude: 144.9634,
    },
    custodyType: FoundItemCustodyTypeEnum.OFFICE,
    status: FoundItemStatusEnum.IN_CUSTODY,
    images: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/An_old_wallet_with_brown_color.jpg',
    ],
    identifyingDetails: 'Contains several cards',
    category: '69cf8c7062a9ba61f8e5fa1b',
    foundBy: new Types.ObjectId('69d4ca5259e9b25307f1fcd6'),
    isPublic: true,
    isActive: true,
    isDeleted: false,
  },
  {
    _id: new Types.ObjectId('6a23d8bdbcbfc47449280465'),
    title: 'Black coin purse',
    description: 'A small black coin purse was found near the reception desk.',
    brand: 'Unknown',
    color: 'Black',
    dateFound: new Date('2026-06-06T11:20:00.000Z'),
    locationFound: 'Reception desk',
    gpsLocation: {
      latitude: -37.814,
      longitude: 144.9635,
    },
    custodyType: FoundItemCustodyTypeEnum.OFFICE,
    status: FoundItemStatusEnum.REPORTED,
    images: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/Wallet_on_ground.jpg',
    ],
    identifyingDetails: 'Small zipper pocket',
    category: '69cf8c7062a9ba61f8e5fa1b',
    foundBy: new Types.ObjectId('69d4ca5259e9b25307f1fcd6'),
    isPublic: true,
    isActive: true,
    isDeleted: false,
  },
  {
    _id: new Types.ObjectId('6a23d8bdbcbfc47449280466'),
    title: 'Blue spiral notebook',
    description:
      'A blue spiral notebook was found in the study area near the library.',
    brand: 'Unknown',
    color: 'Blue',
    dateFound: new Date('2026-06-06T12:00:00.000Z'),
    locationFound: 'Library study area',
    gpsLocation: {
      latitude: -37.8141,
      longitude: 144.9636,
    },
    custodyType: FoundItemCustodyTypeEnum.OFFICE,
    status: FoundItemStatusEnum.REPORTED,
    images: [
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Notebooks-rainbow.jpg/250px-Notebooks-rainbow.jpg',
    ],
    identifyingDetails: 'Contains handwritten lecture notes',
    category: '69cf8c6262a9ba61f8e5fa16',
    foundBy: new Types.ObjectId('69d4ca5259e9b25307f1fcd6'),
    isPublic: true,
    isActive: true,
    isDeleted: false,
  },
  {
    _id: new Types.ObjectId('6a23d8bdbcbfc47449280467'),
    title: 'Calculus textbook',
    description:
      'A mathematics calculus textbook was found in Classroom B after the morning lecture.',
    brand: 'Unknown',
    color: 'Green',
    dateFound: new Date('2026-06-05T05:30:00.000Z'),
    locationFound: 'Classroom B',
    gpsLocation: {
      latitude: -37.8142,
      longitude: 144.9637,
    },
    custodyType: FoundItemCustodyTypeEnum.OFFICE,
    status: FoundItemStatusEnum.REPORTED,
    images: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/Paperback_book_with_green_cover.jpg',
    ],
    identifyingDetails: 'Green cover with notes inside',
    category: '69cf8c6262a9ba61f8e5fa16',
    foundBy: new Types.ObjectId('69d4ca5259e9b25307f1fcd6'),
    isPublic: true,
    isActive: true,
    isDeleted: false,
  },
  {
    _id: new Types.ObjectId('6a23d8bdbcbfc47449280468'),
    title: 'Test item umbrella',
    description: 'A plain black umbrella was found near the main entrance.',
    brand: 'Unknown',
    color: 'Black',
    dateFound: new Date('2026-06-06T13:00:00.000Z'),
    locationFound: 'Main entrance',
    gpsLocation: {
      latitude: -37.8143,
      longitude: 144.9638,
    },
    custodyType: FoundItemCustodyTypeEnum.OFFICE,
    status: FoundItemStatusEnum.REPORTED,
    images: [
      'https://commons.wikimedia.org/wiki/Special:FilePath/Not_fully_opened_umbrella_from_inside.jpg',
    ],
    identifyingDetails: 'Foldable umbrella with curved handle',
    category: '69f9940a8a22591f9eb649a3',
    foundBy: new Types.ObjectId('69d4ca5259e9b25307f1fcd6'),
    isPublic: true,
    isActive: true,
    isDeleted: false,
  },
];
